//! XRPL transaction types.
//!
//! Every transaction on the XRP Ledger has a type, common fields shared by all
//! transactions, and type-specific fields. This module defines all of them.

pub mod account;
pub mod amm;
pub mod clawback;
pub mod credential;
pub mod did;
pub mod escrow;
pub mod flags;
pub mod mpt;
pub mod nft;
pub mod offer;
pub mod oracle;
pub mod payment;
pub mod payment_channel;
pub mod trust_set;
pub mod xchain;

use serde::{Deserialize, Serialize};
use xrpl_types::{AccountId, Amount, Blob, Hash256};

// Re-export all transaction types for convenience
pub use account::{AccountDelete, AccountSet, DepositPreauth, SetRegularKey, SignerListSet, TicketCreate};
pub use amm::{AMMBid, AMMClawback, AMMCreate, AMMDelete, AMMDeposit, AMMVote, AMMWithdraw};
pub use clawback::Clawback;
pub use credential::{CredentialAccept, CredentialCreate, CredentialDelete};
pub use did::{DIDDelete, DIDSet};
pub use escrow::{EscrowCancel, EscrowCreate, EscrowFinish};
pub use mpt::{MPTokenAuthorize, MPTokenIssuanceCreate, MPTokenIssuanceDestroy, MPTokenIssuanceSet};
pub use nft::{NFTokenAcceptOffer, NFTokenBurn, NFTokenCancelOffer, NFTokenCreateOffer, NFTokenMint, NFTokenModify};
pub use offer::{OfferCancel, OfferCreate};
pub use oracle::{OracleDelete, OracleSet};
pub use payment::{CheckCancel, CheckCash, CheckCreate, Payment};
pub use payment_channel::{PaymentChannelClaim, PaymentChannelCreate, PaymentChannelFund};
pub use trust_set::TrustSet;
pub use xchain::{
    XChainAccountCreateCommit, XChainAddAccountCreateAttestation, XChainAddClaimAttestation,
    XChainClaim, XChainCommit, XChainCreateBridge, XChainCreateClaimID, XChainModifyBridge,
};

/// Transaction type discriminator codes from definitions.json.
///
/// These are the `UInt16` values serialized in the `TransactionType` field.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[non_exhaustive]
#[repr(u16)]
pub enum TransactionType {
    Payment = 0,
    EscrowCreate = 1,
    EscrowFinish = 2,
    AccountSet = 3,
    EscrowCancel = 4,
    SetRegularKey = 5,
    OfferCreate = 7,
    OfferCancel = 8,
    TicketCreate = 10,
    SignerListSet = 12,
    PaymentChannelCreate = 13,
    PaymentChannelFund = 14,
    PaymentChannelClaim = 15,
    CheckCreate = 16,
    CheckCash = 17,
    CheckCancel = 18,
    DepositPreauth = 19,
    TrustSet = 20,
    AccountDelete = 21,
    NFTokenMint = 25,
    NFTokenBurn = 26,
    NFTokenCreateOffer = 27,
    NFTokenCancelOffer = 28,
    NFTokenAcceptOffer = 29,
    Clawback = 30,
    AMMClawback = 31,
    AMMCreate = 35,
    AMMDeposit = 36,
    AMMWithdraw = 37,
    AMMVote = 38,
    AMMBid = 39,
    AMMDelete = 40,
    XChainCreateClaimID = 41,
    XChainCommit = 42,
    XChainClaim = 43,
    XChainAccountCreateCommit = 44,
    XChainAddClaimAttestation = 45,
    XChainAddAccountCreateAttestation = 46,
    XChainModifyBridge = 47,
    XChainCreateBridge = 48,
    DIDSet = 49,
    DIDDelete = 50,
    OracleSet = 51,
    OracleDelete = 52,
    LedgerStateFix = 53,
    MPTokenIssuanceCreate = 54,
    MPTokenIssuanceDestroy = 55,
    MPTokenIssuanceSet = 56,
    MPTokenAuthorize = 57,
    CredentialCreate = 58,
    CredentialAccept = 59,
    CredentialDelete = 60,
    NFTokenModify = 61,
    PermissionedDomainSet = 62,
    PermissionedDomainDelete = 63,
    DelegateSet = 64,
    VaultCreate = 65,
    VaultSet = 66,
    VaultDelete = 67,
    VaultDeposit = 68,
    VaultWithdraw = 69,
    VaultClawback = 70,
    Batch = 71,
    LoanBrokerSet = 74,
    LoanBrokerDelete = 75,
    LoanBrokerCoverDeposit = 76,
    LoanBrokerCoverWithdraw = 77,
    LoanBrokerCoverClawback = 78,
    LoanSet = 80,
    LoanDelete = 81,
    LoanManage = 82,
    LoanPay = 84,
}

/// Pseudo-transaction types (generated by validators, not user-submitted).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[non_exhaustive]
#[repr(u16)]
pub enum PseudoTransactionType {
    EnableAmendment = 100,
    SetFee = 101,
    UNLModify = 102,
}

/// Fields common to all transactions.
///
/// Every transaction on the XRPL includes these fields. Type-specific fields
/// are defined in each transaction's own struct.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TransactionCommon {
    /// The unique address of the account that initiated the transaction.
    #[serde(rename = "Account")]
    pub account: AccountId,

    /// The XRP fee to destroy (in drops).
    #[serde(rename = "Fee")]
    pub fee: Amount,

    /// The sequence number of the account. 0 if using Tickets.
    #[serde(rename = "Sequence")]
    pub sequence: u32,

    /// Bit-flags for this transaction.
    #[serde(rename = "Flags", default, skip_serializing_if = "Option::is_none")]
    pub flags: Option<u32>,

    /// Highest ledger index this transaction can appear in.
    #[serde(
        rename = "LastLedgerSequence",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub last_ledger_sequence: Option<u32>,

    /// Hash of a previous transaction from this account.
    #[serde(rename = "AccountTxnID", default, skip_serializing_if = "Option::is_none")]
    pub account_txn_id: Option<Hash256>,

    /// Array of memo objects.
    #[serde(rename = "Memos", default, skip_serializing_if = "Option::is_none")]
    pub memos: Option<Vec<Memo>>,

    /// Network ID for non-mainnet chains.
    #[serde(rename = "NetworkID", default, skip_serializing_if = "Option::is_none")]
    pub network_id: Option<u32>,

    /// Arbitrary source tag.
    #[serde(rename = "SourceTag", default, skip_serializing_if = "Option::is_none")]
    pub source_tag: Option<u32>,

    /// The public key corresponding to the signing key.
    #[serde(rename = "SigningPubKey", default, skip_serializing_if = "Option::is_none")]
    pub signing_pub_key: Option<Blob>,

    /// The transaction signature.
    #[serde(rename = "TxnSignature", default, skip_serializing_if = "Option::is_none")]
    pub txn_signature: Option<Blob>,

    /// Ticket to use instead of Sequence.
    #[serde(
        rename = "TicketSequence",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub ticket_sequence: Option<u32>,

    /// Array of multi-sign Signers.
    #[serde(rename = "Signers", default, skip_serializing_if = "Option::is_none")]
    pub signers: Option<Vec<Signer>>,
}

/// A memo attached to a transaction.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Memo {
    /// The type of memo (conventionally a MIME type).
    #[serde(rename = "MemoType", default, skip_serializing_if = "Option::is_none")]
    pub memo_type: Option<Blob>,

    /// The memo content.
    #[serde(rename = "MemoData", default, skip_serializing_if = "Option::is_none")]
    pub memo_data: Option<Blob>,

    /// The memo format.
    #[serde(rename = "MemoFormat", default, skip_serializing_if = "Option::is_none")]
    pub memo_format: Option<Blob>,
}

/// A signer in a multi-signed transaction.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Signer {
    /// The signer's account.
    #[serde(rename = "Account")]
    pub account: AccountId,

    /// The signer's signature.
    #[serde(rename = "TxnSignature")]
    pub txn_signature: Blob,

    /// The signer's public key.
    #[serde(rename = "SigningPubKey")]
    pub signing_pub_key: Blob,
}

/// Helper macro for implementing common() and common_mut() across all variants.
macro_rules! impl_transaction_accessors {
    ($($variant:ident),+ $(,)?) => {
        /// Get a reference to the common fields shared by all transaction types.
        pub fn common(&self) -> &TransactionCommon {
            match self {
                $(Transaction::$variant { common, .. } => common,)+
                Transaction::Unknown { common, .. } => common,
            }
        }

        /// Get a mutable reference to the common fields.
        pub fn common_mut(&mut self) -> &mut TransactionCommon {
            match self {
                $(Transaction::$variant { common, .. } => common,)+
                Transaction::Unknown { common, .. } => common,
            }
        }

        /// Get the transaction type discriminator.
        pub fn transaction_type(&self) -> &str {
            match self {
                $(Transaction::$variant { .. } => stringify!($variant),)+
                Transaction::Unknown { transaction_type, .. } => transaction_type,
            }
        }
    };
}

/// A fully-typed XRPL transaction combining common and type-specific fields.
///
/// This enum provides a single entry point for deserializing any XRPL transaction
/// from JSON. The `TransactionType` field in the JSON determines which variant
/// is constructed.
///
/// For transaction types without a dedicated struct (e.g., newer amendment-gated
/// types), the `Unknown` variant preserves the full JSON map.
///
/// # Examples
///
/// ```
/// # use serde_json::json;
/// # use xrpl_models::transactions::Transaction;
/// let json = json!({
///     "TransactionType": "Payment",
///     "Account": "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh",
///     "Fee": "12",
///     "Sequence": 1,
///     "Destination": "rPT1Sjq2YGrBMTttX4GZHjKu9dyfzbpAYe",
///     "Amount": "1000000"
/// });
///
/// let tx: Transaction = serde_json::from_value(json).unwrap();
/// assert_eq!(tx.transaction_type(), "Payment");
/// assert_eq!(tx.common().sequence, 1);
/// ```
#[derive(Debug, Clone, PartialEq)]
#[non_exhaustive]
pub enum Transaction {
    Payment { common: TransactionCommon, fields: Payment },
    EscrowCreate { common: TransactionCommon, fields: EscrowCreate },
    EscrowFinish { common: TransactionCommon, fields: EscrowFinish },
    AccountSet { common: TransactionCommon, fields: AccountSet },
    EscrowCancel { common: TransactionCommon, fields: EscrowCancel },
    SetRegularKey { common: TransactionCommon, fields: SetRegularKey },
    OfferCreate { common: TransactionCommon, fields: OfferCreate },
    OfferCancel { common: TransactionCommon, fields: OfferCancel },
    TicketCreate { common: TransactionCommon, fields: TicketCreate },
    SignerListSet { common: TransactionCommon, fields: SignerListSet },
    PaymentChannelCreate { common: TransactionCommon, fields: PaymentChannelCreate },
    PaymentChannelFund { common: TransactionCommon, fields: PaymentChannelFund },
    PaymentChannelClaim { common: TransactionCommon, fields: PaymentChannelClaim },
    CheckCreate { common: TransactionCommon, fields: CheckCreate },
    CheckCash { common: TransactionCommon, fields: CheckCash },
    CheckCancel { common: TransactionCommon, fields: CheckCancel },
    DepositPreauth { common: TransactionCommon, fields: DepositPreauth },
    TrustSet { common: TransactionCommon, fields: TrustSet },
    AccountDelete { common: TransactionCommon, fields: AccountDelete },
    NFTokenMint { common: TransactionCommon, fields: NFTokenMint },
    NFTokenBurn { common: TransactionCommon, fields: NFTokenBurn },
    NFTokenCreateOffer { common: TransactionCommon, fields: NFTokenCreateOffer },
    NFTokenCancelOffer { common: TransactionCommon, fields: NFTokenCancelOffer },
    NFTokenAcceptOffer { common: TransactionCommon, fields: NFTokenAcceptOffer },
    NFTokenModify { common: TransactionCommon, fields: NFTokenModify },
    Clawback { common: TransactionCommon, fields: Clawback },
    AMMClawback { common: TransactionCommon, fields: AMMClawback },
    AMMCreate { common: TransactionCommon, fields: AMMCreate },
    AMMDeposit { common: TransactionCommon, fields: AMMDeposit },
    AMMWithdraw { common: TransactionCommon, fields: AMMWithdraw },
    AMMVote { common: TransactionCommon, fields: AMMVote },
    AMMBid { common: TransactionCommon, fields: AMMBid },
    AMMDelete { common: TransactionCommon, fields: AMMDelete },
    XChainCreateClaimID { common: TransactionCommon, fields: XChainCreateClaimID },
    XChainCommit { common: TransactionCommon, fields: XChainCommit },
    XChainClaim { common: TransactionCommon, fields: XChainClaim },
    XChainAccountCreateCommit { common: TransactionCommon, fields: XChainAccountCreateCommit },
    XChainAddClaimAttestation { common: TransactionCommon, fields: XChainAddClaimAttestation },
    XChainAddAccountCreateAttestation { common: TransactionCommon, fields: XChainAddAccountCreateAttestation },
    XChainModifyBridge { common: TransactionCommon, fields: XChainModifyBridge },
    XChainCreateBridge { common: TransactionCommon, fields: XChainCreateBridge },
    DIDSet { common: TransactionCommon, fields: DIDSet },
    DIDDelete { common: TransactionCommon, fields: DIDDelete },
    OracleSet { common: TransactionCommon, fields: OracleSet },
    OracleDelete { common: TransactionCommon, fields: OracleDelete },
    MPTokenIssuanceCreate { common: TransactionCommon, fields: MPTokenIssuanceCreate },
    MPTokenIssuanceDestroy { common: TransactionCommon, fields: MPTokenIssuanceDestroy },
    MPTokenIssuanceSet { common: TransactionCommon, fields: MPTokenIssuanceSet },
    MPTokenAuthorize { common: TransactionCommon, fields: MPTokenAuthorize },
    CredentialCreate { common: TransactionCommon, fields: CredentialCreate },
    CredentialAccept { common: TransactionCommon, fields: CredentialAccept },
    CredentialDelete { common: TransactionCommon, fields: CredentialDelete },
    /// Catch-all for transaction types without a dedicated struct.
    Unknown {
        common: TransactionCommon,
        transaction_type: String,
        extra: serde_json::Map<String, serde_json::Value>,
    },
}

impl Transaction {
    impl_transaction_accessors!(
        Payment,
        EscrowCreate,
        EscrowFinish,
        AccountSet,
        EscrowCancel,
        SetRegularKey,
        OfferCreate,
        OfferCancel,
        TicketCreate,
        SignerListSet,
        PaymentChannelCreate,
        PaymentChannelFund,
        PaymentChannelClaim,
        CheckCreate,
        CheckCash,
        CheckCancel,
        DepositPreauth,
        TrustSet,
        AccountDelete,
        NFTokenMint,
        NFTokenBurn,
        NFTokenCreateOffer,
        NFTokenCancelOffer,
        NFTokenAcceptOffer,
        NFTokenModify,
        Clawback,
        AMMClawback,
        AMMCreate,
        AMMDeposit,
        AMMWithdraw,
        AMMVote,
        AMMBid,
        AMMDelete,
        XChainCreateClaimID,
        XChainCommit,
        XChainClaim,
        XChainAccountCreateCommit,
        XChainAddClaimAttestation,
        XChainAddAccountCreateAttestation,
        XChainModifyBridge,
        XChainCreateBridge,
        DIDSet,
        DIDDelete,
        OracleSet,
        OracleDelete,
        MPTokenIssuanceCreate,
        MPTokenIssuanceDestroy,
        MPTokenIssuanceSet,
        MPTokenAuthorize,
        CredentialCreate,
        CredentialAccept,
        CredentialDelete,
    );
}

impl Serialize for Transaction {
    fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        // Serialize to a JSON Value, merge common + type-specific + TransactionType
        let common_val = serde_json::to_value(self.common()).map_err(serde::ser::Error::custom)?;
        let mut map = common_val
            .as_object()
            .cloned()
            .unwrap_or_default();

        // Add TransactionType
        map.insert(
            "TransactionType".to_string(),
            serde_json::Value::String(self.transaction_type().to_string()),
        );

        // Add type-specific fields
        macro_rules! merge_fields {
            ($fields:expr) => {{
                let fields_val = serde_json::to_value($fields).map_err(serde::ser::Error::custom)?;
                if let Some(obj) = fields_val.as_object() {
                    for (k, v) in obj {
                        map.insert(k.clone(), v.clone());
                    }
                }
            }};
        }

        match self {
            Transaction::Payment { fields, .. } => merge_fields!(fields),
            Transaction::EscrowCreate { fields, .. } => merge_fields!(fields),
            Transaction::EscrowFinish { fields, .. } => merge_fields!(fields),
            Transaction::AccountSet { fields, .. } => merge_fields!(fields),
            Transaction::EscrowCancel { fields, .. } => merge_fields!(fields),
            Transaction::SetRegularKey { fields, .. } => merge_fields!(fields),
            Transaction::OfferCreate { fields, .. } => merge_fields!(fields),
            Transaction::OfferCancel { fields, .. } => merge_fields!(fields),
            Transaction::TicketCreate { fields, .. } => merge_fields!(fields),
            Transaction::SignerListSet { fields, .. } => merge_fields!(fields),
            Transaction::PaymentChannelCreate { fields, .. } => merge_fields!(fields),
            Transaction::PaymentChannelFund { fields, .. } => merge_fields!(fields),
            Transaction::PaymentChannelClaim { fields, .. } => merge_fields!(fields),
            Transaction::CheckCreate { fields, .. } => merge_fields!(fields),
            Transaction::CheckCash { fields, .. } => merge_fields!(fields),
            Transaction::CheckCancel { fields, .. } => merge_fields!(fields),
            Transaction::DepositPreauth { fields, .. } => merge_fields!(fields),
            Transaction::TrustSet { fields, .. } => merge_fields!(fields),
            Transaction::AccountDelete { fields, .. } => merge_fields!(fields),
            Transaction::NFTokenMint { fields, .. } => merge_fields!(fields),
            Transaction::NFTokenBurn { fields, .. } => merge_fields!(fields),
            Transaction::NFTokenCreateOffer { fields, .. } => merge_fields!(fields),
            Transaction::NFTokenCancelOffer { fields, .. } => merge_fields!(fields),
            Transaction::NFTokenAcceptOffer { fields, .. } => merge_fields!(fields),
            Transaction::NFTokenModify { fields, .. } => merge_fields!(fields),
            Transaction::Clawback { fields, .. } => merge_fields!(fields),
            Transaction::AMMClawback { fields, .. } => merge_fields!(fields),
            Transaction::AMMCreate { fields, .. } => merge_fields!(fields),
            Transaction::AMMDeposit { fields, .. } => merge_fields!(fields),
            Transaction::AMMWithdraw { fields, .. } => merge_fields!(fields),
            Transaction::AMMVote { fields, .. } => merge_fields!(fields),
            Transaction::AMMBid { fields, .. } => merge_fields!(fields),
            Transaction::AMMDelete { fields, .. } => merge_fields!(fields),
            Transaction::XChainCreateClaimID { fields, .. } => merge_fields!(fields),
            Transaction::XChainCommit { fields, .. } => merge_fields!(fields),
            Transaction::XChainClaim { fields, .. } => merge_fields!(fields),
            Transaction::XChainAccountCreateCommit { fields, .. } => merge_fields!(fields),
            Transaction::XChainAddClaimAttestation { fields, .. } => merge_fields!(fields),
            Transaction::XChainAddAccountCreateAttestation { fields, .. } => merge_fields!(fields),
            Transaction::XChainModifyBridge { fields, .. } => merge_fields!(fields),
            Transaction::XChainCreateBridge { fields, .. } => merge_fields!(fields),
            Transaction::DIDSet { fields, .. } => merge_fields!(fields),
            Transaction::DIDDelete { fields, .. } => merge_fields!(fields),
            Transaction::OracleSet { fields, .. } => merge_fields!(fields),
            Transaction::OracleDelete { fields, .. } => merge_fields!(fields),
            Transaction::MPTokenIssuanceCreate { fields, .. } => merge_fields!(fields),
            Transaction::MPTokenIssuanceDestroy { fields, .. } => merge_fields!(fields),
            Transaction::MPTokenIssuanceSet { fields, .. } => merge_fields!(fields),
            Transaction::MPTokenAuthorize { fields, .. } => merge_fields!(fields),
            Transaction::CredentialCreate { fields, .. } => merge_fields!(fields),
            Transaction::CredentialAccept { fields, .. } => merge_fields!(fields),
            Transaction::CredentialDelete { fields, .. } => merge_fields!(fields),
            Transaction::Unknown { extra, .. } => {
                for (k, v) in extra {
                    map.insert(k.clone(), v.clone());
                }
            }
        }

        map.serialize(serializer)
    }
}

impl<'de> Deserialize<'de> for Transaction {
    fn deserialize<D: serde::Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let value = serde_json::Value::deserialize(deserializer)?;
        let map = value
            .as_object()
            .ok_or_else(|| serde::de::Error::custom("transaction must be a JSON object"))?;

        let tx_type = map
            .get("TransactionType")
            .and_then(|v| v.as_str())
            .ok_or_else(|| serde::de::Error::custom("missing or invalid TransactionType"))?;

        let common: TransactionCommon =
            serde_json::from_value(value.clone()).map_err(serde::de::Error::custom)?;

        macro_rules! deser_variant {
            ($variant:ident, $type:ty) => {{
                let fields: $type =
                    serde_json::from_value(value).map_err(serde::de::Error::custom)?;
                Ok(Transaction::$variant { common, fields })
            }};
        }

        match tx_type {
            "Payment" => deser_variant!(Payment, payment::Payment),
            "EscrowCreate" => deser_variant!(EscrowCreate, escrow::EscrowCreate),
            "EscrowFinish" => deser_variant!(EscrowFinish, escrow::EscrowFinish),
            "AccountSet" => deser_variant!(AccountSet, account::AccountSet),
            "EscrowCancel" => deser_variant!(EscrowCancel, escrow::EscrowCancel),
            "SetRegularKey" => deser_variant!(SetRegularKey, account::SetRegularKey),
            "OfferCreate" => deser_variant!(OfferCreate, offer::OfferCreate),
            "OfferCancel" => deser_variant!(OfferCancel, offer::OfferCancel),
            "TicketCreate" => deser_variant!(TicketCreate, account::TicketCreate),
            "SignerListSet" => deser_variant!(SignerListSet, account::SignerListSet),
            "PaymentChannelCreate" => deser_variant!(PaymentChannelCreate, payment_channel::PaymentChannelCreate),
            "PaymentChannelFund" => deser_variant!(PaymentChannelFund, payment_channel::PaymentChannelFund),
            "PaymentChannelClaim" => deser_variant!(PaymentChannelClaim, payment_channel::PaymentChannelClaim),
            "CheckCreate" => deser_variant!(CheckCreate, payment::CheckCreate),
            "CheckCash" => deser_variant!(CheckCash, payment::CheckCash),
            "CheckCancel" => deser_variant!(CheckCancel, payment::CheckCancel),
            "DepositPreauth" => deser_variant!(DepositPreauth, account::DepositPreauth),
            "TrustSet" => deser_variant!(TrustSet, trust_set::TrustSet),
            "AccountDelete" => deser_variant!(AccountDelete, account::AccountDelete),
            "NFTokenMint" => deser_variant!(NFTokenMint, nft::NFTokenMint),
            "NFTokenBurn" => deser_variant!(NFTokenBurn, nft::NFTokenBurn),
            "NFTokenCreateOffer" => deser_variant!(NFTokenCreateOffer, nft::NFTokenCreateOffer),
            "NFTokenCancelOffer" => deser_variant!(NFTokenCancelOffer, nft::NFTokenCancelOffer),
            "NFTokenAcceptOffer" => deser_variant!(NFTokenAcceptOffer, nft::NFTokenAcceptOffer),
            "NFTokenModify" => deser_variant!(NFTokenModify, nft::NFTokenModify),
            "Clawback" => deser_variant!(Clawback, clawback::Clawback),
            "AMMClawback" => deser_variant!(AMMClawback, amm::AMMClawback),
            "AMMCreate" => deser_variant!(AMMCreate, amm::AMMCreate),
            "AMMDeposit" => deser_variant!(AMMDeposit, amm::AMMDeposit),
            "AMMWithdraw" => deser_variant!(AMMWithdraw, amm::AMMWithdraw),
            "AMMVote" => deser_variant!(AMMVote, amm::AMMVote),
            "AMMBid" => deser_variant!(AMMBid, amm::AMMBid),
            "AMMDelete" => deser_variant!(AMMDelete, amm::AMMDelete),
            "XChainCreateClaimID" => deser_variant!(XChainCreateClaimID, xchain::XChainCreateClaimID),
            "XChainCommit" => deser_variant!(XChainCommit, xchain::XChainCommit),
            "XChainClaim" => deser_variant!(XChainClaim, xchain::XChainClaim),
            "XChainAccountCreateCommit" => deser_variant!(XChainAccountCreateCommit, xchain::XChainAccountCreateCommit),
            "XChainAddClaimAttestation" => deser_variant!(XChainAddClaimAttestation, xchain::XChainAddClaimAttestation),
            "XChainAddAccountCreateAttestation" => deser_variant!(XChainAddAccountCreateAttestation, xchain::XChainAddAccountCreateAttestation),
            "XChainModifyBridge" => deser_variant!(XChainModifyBridge, xchain::XChainModifyBridge),
            "XChainCreateBridge" => deser_variant!(XChainCreateBridge, xchain::XChainCreateBridge),
            "DIDSet" => deser_variant!(DIDSet, did::DIDSet),
            "DIDDelete" => deser_variant!(DIDDelete, did::DIDDelete),
            "OracleSet" => deser_variant!(OracleSet, oracle::OracleSet),
            "OracleDelete" => deser_variant!(OracleDelete, oracle::OracleDelete),
            "MPTokenIssuanceCreate" => deser_variant!(MPTokenIssuanceCreate, mpt::MPTokenIssuanceCreate),
            "MPTokenIssuanceDestroy" => deser_variant!(MPTokenIssuanceDestroy, mpt::MPTokenIssuanceDestroy),
            "MPTokenIssuanceSet" => deser_variant!(MPTokenIssuanceSet, mpt::MPTokenIssuanceSet),
            "MPTokenAuthorize" => deser_variant!(MPTokenAuthorize, mpt::MPTokenAuthorize),
            "CredentialCreate" => deser_variant!(CredentialCreate, credential::CredentialCreate),
            "CredentialAccept" => deser_variant!(CredentialAccept, credential::CredentialAccept),
            "CredentialDelete" => deser_variant!(CredentialDelete, credential::CredentialDelete),
            other => {
                // Unknown transaction type — preserve the full JSON
                let extra = map.clone();
                Ok(Transaction::Unknown {
                    common,
                    transaction_type: other.to_string(),
                    extra,
                })
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn deserialize_payment() {
        let json = json!({
            "TransactionType": "Payment",
            "Account": "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh",
            "Fee": "12",
            "Sequence": 1,
            "Destination": "rPT1Sjq2YGrBMTttX4GZHjKu9dyfzbpAYe",
            "Amount": "1000000"
        });

        let tx: Transaction = serde_json::from_value(json).expect("should deserialize");
        assert_eq!(tx.transaction_type(), "Payment");
        assert_eq!(tx.common().sequence, 1);

        if let Transaction::Payment { fields, .. } = &tx {
            assert_eq!(fields.amount, Amount::Xrp(xrpl_types::XrpAmount::from_drops(1_000_000).unwrap()));
        } else {
            panic!("expected Payment variant");
        }
    }

    #[test]
    fn round_trip_payment() {
        let json = json!({
            "TransactionType": "Payment",
            "Account": "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh",
            "Fee": "12",
            "Sequence": 1,
            "Destination": "rPT1Sjq2YGrBMTttX4GZHjKu9dyfzbpAYe",
            "Amount": "1000000"
        });

        let tx: Transaction = serde_json::from_value(json.clone()).expect("deser");
        let serialized = serde_json::to_value(&tx).expect("ser");

        // Verify key fields survived the round-trip
        let map = serialized.as_object().expect("obj");
        assert_eq!(map.get("TransactionType").and_then(|v| v.as_str()), Some("Payment"));
        assert_eq!(map.get("Account").and_then(|v| v.as_str()), Some("rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh"));
        assert_eq!(map.get("Sequence").and_then(|v| v.as_u64()), Some(1));
        assert_eq!(map.get("Amount").and_then(|v| v.as_str()), Some("1000000"));
        assert_eq!(map.get("Destination").and_then(|v| v.as_str()), Some("rPT1Sjq2YGrBMTttX4GZHjKu9dyfzbpAYe"));
    }

    #[test]
    fn deserialize_unknown_type() {
        let json = json!({
            "TransactionType": "FutureTxType",
            "Account": "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh",
            "Fee": "12",
            "Sequence": 1,
            "SomeFutureField": "value"
        });

        let tx: Transaction = serde_json::from_value(json).expect("should deserialize");
        assert_eq!(tx.transaction_type(), "FutureTxType");
        assert_eq!(tx.common().sequence, 1);

        if let Transaction::Unknown { extra, .. } = &tx {
            assert_eq!(extra.get("SomeFutureField").and_then(|v| v.as_str()), Some("value"));
        } else {
            panic!("expected Unknown variant");
        }
    }

    #[test]
    fn common_accessor() {
        let json = json!({
            "TransactionType": "OfferCreate",
            "Account": "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh",
            "Fee": "12",
            "Sequence": 42,
            "TakerPays": "5000000",
            "TakerGets": "1000000"
        });

        let tx: Transaction = serde_json::from_value(json).expect("deser");
        assert_eq!(tx.common().sequence, 42);
        assert_eq!(
            tx.common().account,
            "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh".parse().expect("addr")
        );
    }
}
